name: crypto-trading-news

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: "0 20 * * *"   # Run daily at 20:00 UTC (3AM UTC+7)

jobs:
  build:
    if: github.event_name != 'schedule'   # only run on push or manual
    runs-on: self-hosted
    environment: production

    env:
      # TWITTER
      TWITTER_COOKIES: ${{ secrets.TWITTER_COOKIES }}
      # Tor
      TOR_PROXY_URL: ${{ vars.TOR_PROXY_URL }}
      TOR_PROXY_NUM_PORTS: ${{ vars.TOR_PROXY_NUM_PORTS }}
      MAX_CIRCUIT_DIRTINESS: ${{ vars.MAX_CIRCUIT_DIRTINESS }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        working-directory: ${{ github.workspace }}
        run: |
          echo "Installing system dependencies inside: $(pwd)"
          bash install.sh

      - name: Create local .env 
        working-directory: ${{ github.workspace }}
        run: |
          echo "Creating local .env in $(pwd)"
          touch .env
          echo "${{ secrets.ENV_FILE }}" > .env
          echo "TOR_PROXY_URL=$TOR_PROXY_URL" >> .env
          echo "TOR_PROXY_NUM_PORTS=$TOR_PROXY_NUM_PORTS" >> .env
          echo "TWITTER_COOKIES=$TWITTER_COOKIES" >> .env

      - name: Start with PM2
        working-directory: ${{ github.workspace }}
        run: |
          pm2 delete all --namespace crypto-news || true
          RUNNER_TRACKING_ID="" NUM_PORTS=${TOR_PROXY_NUM_PORTS:-1} MAX_CIRCUIT=${MAX_CIRCUIT_DIRTINESS:-600} \
            pm2 start ecosystem.config.js --only tor-multi,crypto-trading-news --namespace crypto-news
          pm2 save --namespace crypto-news

  restart:
    if: github.event_name == 'schedule'   # only run on cron schedule
    runs-on: self-hosted
    environment: production

    steps:
      - name: Restart PM2 apps
        run: |
          echo "Restarting apps via PM2..."
          pm2 restart all --namespace crypto-news || true
          pm2 save --namespace crypto-news
