name: crypto-trading-news

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        working-directory: ${{ github.workspace }}
        run: |
          echo "Installing system dependencies inside: $(pwd)"
          bash install.sh

      - name: Create local .env 
        working-directory: ${{ github.workspace }}
        run: |
          echo "Creating local .env in $(pwd)"
          touch .env
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Trigger with PM2
        working-directory: ${{ github.workspace }}
        run: |
          pm2 delete all || true
          RUNNER_TRACKING_ID="" && NUM_PORTS=${NUM_PORTS:-1} MAX_CIRCUIT=${MAX_CIRCUIT_DIRTINESS:-600} pm2 start ecosystem.config.js
          pm2 save